tenantName: ""
# ingressDomain is the suffix for each per-apiserver ingress host.
ingressDomain: ""
# upstreams is the list of on-prem apiserver hosts to expose.
upstreams: []

ingressClassName: external-haproxy

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/kube-oidc-discovery-proxy
  pullPolicy: IfNotPresent
  tag: "main"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
