tenantName: ""
# ingressDomain is the suffix for each per-apiserver ingress host.
ingressDomain: ""
# upstreams is the list of on-prem apiserver hosts to expose.
upstreams: []

ingressClassName: external-haproxy

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/kube-oidc-discovery-proxy
  pullPolicy: IfNotPresent
  tag: "main"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1069
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1069
  runAsGroup: 1069

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 32Mi
    cpu: 10m

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75

nodeSelector: {}

tolerations: []

affinity: {}
